apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: actions.eventreactor.summerwind.github.io
spec:
  group: eventreactor.summerwind.github.io
  names:
    kind: Action
    plural: actions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            event:
              properties:
                kind:
                  type: string
                name:
                  type: string
              required:
              - name
              - kind
              type: object
            notification:
              properties:
                name:
                  type: string
              required:
              - name
              type: object
            pipeline:
              properties:
                generation:
                  format: int64
                  type: integer
                name:
                  type: string
              required:
              - name
              - generation
              type: object
            upstream:
              properties:
                name:
                  type: string
                status:
                  type: string
                via:
                  type: string
              required:
              - name
              - status
              - via
              type: object
          required:
          - event
          - pipeline
          - upstream
          - notification
          type: object
        status:
          properties:
            notificationTime:
              format: date-time
              type: string
            stepLogs:
              items:
                type: string
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
