apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: actions.eventreactor.summerwind.github.io
spec:
  group: eventreactor.summerwind.github.io
  names:
    kind: Action
    plural: actions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            event:
              properties:
                name:
                  type: string
                source:
                  type: string
                type:
                  maxLength: 63
                  minLength: 1
                  pattern: ^[a-z0-9A-Z\-_.]+$
                  type: string
              required:
              - name
              - type
              - source
              type: object
            pipeline:
              properties:
                generation:
                  format: int64
                  type: integer
                name:
                  type: string
              required:
              - name
              - generation
              type: object
            transaction:
              properties:
                id:
                  type: string
                stage:
                  format: int64
                  type: integer
              required:
              - id
              - stage
              type: object
            upstream:
              properties:
                name:
                  type: string
                pipeline:
                  type: string
                status:
                  enum:
                  - success
                  - failure
                  type: string
                via:
                  items:
                    type: string
                  maxItems: 10
                  type: array
              required:
              - name
              - status
              - pipeline
              type: object
          required:
          - event
          - pipeline
          - upstream
          - transaction
          type: object
        status:
          properties:
            dispatchTime:
              format: date-time
              type: string
            stepLogs:
              items:
                type: string
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
