apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: events.eventreactor.summerwind.github.io
spec:
  group: eventreactor.summerwind.github.io
  names:
    kind: Event
    plural: events
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            contentType:
              type: string
            data:
              type: string
            id:
              minLength: 1
              type: string
            schemeURL:
              type: string
            source:
              minLength: 1
              type: string
            specVersion:
              enum:
              - "0.2"
              type: string
            time:
              format: date-time
              type: string
            type:
              maxLength: 63
              minLength: 1
              pattern: ^[a-z0-9A-Z\-_.]+$
              type: string
          required:
          - specVersion
          - type
          - source
          - id
          type: object
        status:
          properties:
            dispatchTime:
              format: date-time
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
