apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelines.eventreactor.summerwind.github.io
spec:
  group: eventreactor.summerwind.github.io
  names:
    kind: Pipeline
    plural: pipelines
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            trigger:
              properties:
                event:
                  properties:
                    source:
                      minLength: 1
                      type: string
                    type:
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-z0-9A-Z\-_.]+$
                      type: string
                  required:
                  - type
                  - source
                  type: object
                pipeline:
                  properties:
                    name:
                      type: string
                    selector:
                      type: object
                    status:
                      type: string
                  required:
                  - name
                  - selector
                  type: object
              type: object
          required:
          - trigger
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
