apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelines.eventreactor.summerwind.github.io
spec:
  group: eventreactor.summerwind.github.io
  names:
    kind: Pipeline
    plural: pipelines
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            trigger:
              properties:
                event:
                  properties:
                    source:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - source
                  type: object
              required:
              - event
              type: object
          required:
          - trigger
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
