apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: events.eventreactor.summerwind.github.io
spec:
  group: eventreactor.summerwind.github.io
  names:
    kind: Event
    plural: events
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cloudEventsVersion:
              type: string
            contentType:
              type: string
            data:
              type: string
            eventID:
              type: string
            eventTime:
              format: date-time
              type: string
            eventType:
              type: string
            eventTypeVersion:
              type: string
            source:
              type: string
          required:
          - cloudEventsVersion
          - eventID
          - eventType
          - source
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
