apiVersion: eventreactor.summerwind.github.io/v1alpha1
kind: Pipeline
metadata:
  name: eventreactor-build
  labels:
    notification: slack
spec:
  trigger:
    event:
      type: com.github.push
      sourcePattern: summerwind/eventreactor/git/refs/heads/master
  sources:
  - name: git
    targetPath: go/src/github.com/summerwind/eventreactor
    git:
      url: https://github.com/summerwind/eventreactor.git
      revision: master
  steps:
  - name: vendor
    image: summerwind/kubebuilder:latest
    command: ["make"]
    args: ["vendor"]
    workingDir: "/workspace/go/src/github.com/summerwind/eventreactor"
    env:
    - name: GOPATH
      value: /workspace/go
  - name: test
    image: summerwind/kubebuilder:latest
    command: ["make"]
    args: ["test"]
    workingDir: "/workspace/go/src/github.com/summerwind/eventreactor"
    env:
    - name: GOPATH
      value: /workspace/go
  - name: build
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile", "--context=dir:///workspace/go/src/github.com/summerwind/eventreactor", "--no-push"]
  timeout: 60m
