version: 2
jobs:
  build:
    docker:
    - image: summerwind/kubebuilder:latest
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        name: Test
        command: make test
    - run:
        name: Build container
        command: make docker-build

workflows:
  version: 2
  main:
    jobs:
    - build
