version: 2
jobs:
  test:
    docker:
    - image: summerwind/toolbox:latest
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        name: Build container
        command: make docker-build

workflows:
  version: 2
  main:
    jobs:
    - test
