apiVersion: eventreactor.summerwind.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-example
spec:
  trigger:
    type: dev.summerwind.eventreactor.test
    matchSource: /eventreactor/test
  resourceTemplates:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: subscription-example
    data:
      message: hello
