apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: resource-cleaner-role
rules:
- apiGroups:
  - eventreactor.summerwind.github.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - eventreactor.summerwind.github.io
  resources:
  - actions
  verbs:
  - get
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: resource-cleaner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: resource-cleaner-role
subjects:
- kind: ServiceAccount
  name: resource-cleaner
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resource-cleaner
  labels:
    app: eventreactor
spec:
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resource-cleaner
            image: summerwind/eventreactor:latest
            command: ["/bin/resource-cleaner"]
            args:
            - "--namespace"
            - "$(NAMESPACE)"
            - "--event-retention-period"
            - "336h"
            - "--action-retention-period"
            - "336h"
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          serviceAccountName: resource-cleaner
          restartPolicy: Never
