apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventlet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: eventlet
rules:
- apiGroups:
  - eventreactor.summerwind.github.io
  resources:
  - events
  - actions
  verbs:
  - create
  - get
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: eventlet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eventlet
subjects:
- kind: ServiceAccount
  name: eventlet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventlet
  template:
    metadata:
      labels:
        app: eventlet
    spec:
      containers:
      - name: eventlet
        image: summerwind/eventreactor:latest
        imagePullPolicy: Always
        command: ["/bin/eventlet"]
        args:
        - "--namespace"
        - "$(NAMESPACE)"
        - "--event-retention-period"
        - "336h"
        - "--action-retention-period"
        - "336h"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 14380
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      serviceAccountName: eventlet
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eventlet
spec:
  selector:
    app: eventlet
  ports:
  - protocol: TCP
    port: 14380
    targetPort: 14380
